language: ruby
services: mongodb

notifications:
  email: false

rvm:
  - 2.2.2
  
env:
  - "UPLOADS=paperclip"
  - "UPLOADS=carrierwave"

gemfile:
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile

